[package]
name = "libruntime"
version = "0.1.0"
edition = "2024"

[dependencies]
libprotocol = { path = "../libprotocol" }
serde_json = "1.0.149"
sha2 = "0.10.9"
insta = "1.46.3"
serde = { version = "1.0.228", features = ["derive"] }
anyhow = "1.0.101"
