[package]
name = "rload"
version = "0.1.0"
edition = "2024"

[dependencies]
libcli = { path = "../../crates/libcli" }
libprotocol = { path = "../../crates/libprotocol" }
anyhow = "1.0.101"
assert_cmd = "2.1.2"
insta = "1.46.3"
tokio = "1.49.0"

[dev-dependencies]
assert_cmd = "2.1.2"
test_support = { path = "../../crates/test_support" }
